# данный файл используем для настроек RabbitMQ

spring:
  rabbitmq:
    host: rabbitmq # было localhost
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey

# Примечание
# в файле docker-compose.yml мы назначаем сервису rabbitmq
# hostname: rabbitmq, а здесь к нему обращаемся по этому имени